"""create response table

Revision ID: 31c2101d970a
Revises: 48216cbe2e3b
Create Date: 2025-09-15 19:16:37.771807

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "31c2101d970a"
down_revision: Union[str, Sequence[str], None] = "48216cbe2e3b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "responses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("review_id", sa.Integer(), nullable=False),
        sa.Column("reply_text", sa.Text(), nullable=False),
        sa.Column("model", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["review_id"],
            ["reviews.id"],
            name=op.f("fk_responses_review_id_reviews"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_responses")),
    )
    op.create_index(
        op.f("ix_responses_review_id"), "responses", ["review_id"], unique=True
    )
    op.create_index(
        op.f("ix_responses_status"), "responses", ["status"], unique=False
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_responses_status"), table_name="responses")
    op.drop_index(op.f("ix_responses_review_id"), table_name="responses")
    op.drop_table("responses")
    # ### end Alembic commands ###
